#!/usr/bin/env bash

if [ $(id -u) != 0 ]; then
    echo "This script must be ran as root"
    exit 1
fi

set -e                          # Exit if any command fails

try_install() {
    dpkg -l "$1" | grep -q ^ii && return 1
    apt-get -y install "$@"
    return 0
}

# List of packages installed by the script
packages=(
    emacs
    puppet
)

for package in "${packages[@]}"; do
    if try_install "$package"; then
        echo "$package is now installed"
    else
        echo "$package has already been installed"
    fi
done

# Firewall rules
ufw allow ssh
ufw enable --force

# Disable root login over ssh
sed -i -e "s/\(^\|#\)PermitRootLogin.*$/PermitRootLogin prohibit-password/" /etc/ssh/sshd_config

systemctl enable ssh
systemctl start ssh
